mysql:
  host: 127.0.0.1
  port: 3306
  config: ?charset=utf8mb4&parseTime=True&loc=Local
  db: fb
  user: root
  password: "123456"
  log_level: dev
system:
  host: 0.0.0.0
  port: 8080
  env: release
logger:
  level: info
  prefix: '[fb]'
  director: log
  show_line: true
  log_in_console: true